INSERT INTO `rainlab_translate_attributes` (`locale`, `model_id`, `model_type`, `attribute_data`) VALUES
('sk', '1', 'OFFLINE\\GDPR\\Models\\Cookie', '{\"name\":\"\",\"description\":\"<p>Technick\\u00e9 cookies s\\u00fa nevyhnutn\\u00e9 na spr\\u00e1vne fungovanie webu.<\\/p>\\r\\n\",\"contact_links_dpo\":\"null\",\"levels\":\"null\",\"item_details\":\"null\"}'),
('cs', '1', 'OFFLINE\\GDPR\\Models\\Cookie', '{\"name\":\"Technick\\u00e9\",\"description\":\"<p>Technick\\u00e9 cookies jsou nezbytn\\u00e9 pro spr\\u00e1vn\\u00e9 fungov\\u00e1n\\u00ed webu.<\\/p>\",\"contact_links_dpo\":\"[]\",\"levels\":\"[]\",\"item_details\":\"[]\"}'),
('sk', '1', 'OFFLINE\\GDPR\\Models\\CookieGroup', '{\"name\":\"Technické Cookies\",\"description\":\"<p>Technické cookies sa používajú na odlíšenie vašich aktivít na stránke od ostatných požiadaviek na web.<\\/p>\\r\\n\"}'),
('sk', '2', 'OFFLINE\\GDPR\\Models\\Cookie', '{\"name\":\"\",\"description\":\"<p>Tieto cookies s\\u00fa nevyhnutn\\u00e9 pre va\\u0161u registr\\u00e1ciu a odosielanie kontaktn\\u00fdch formul\\u00e1rov.<\\/p>\\r\\n\",\"contact_links_dpo\":\"null\",\"levels\":\"null\",\"item_details\":\"null\"}'),
('cs', '2', 'OFFLINE\\GDPR\\Models\\Cookie', '{\"name\":\"Personalizovan\\u00e9\",\"description\":\"<p>Tyto cookies jsou nezbytn\\u00e9 pro va\\u0161\\u00ed registraci a odes\\u00edl\\u00e1n\\u00ed kontaktn\\u00edch formul\\u00e1\\u0159\\u016f.<\\/p>\",\"contact_links_dpo\":\"[]\",\"levels\":\"[]\",\"item_details\":\"[]\"}'),
('sk', '2', 'OFFLINE\\GDPR\\Models\\CookieGroup', '{\"name\":\"Personalizované Cookies\",\"description\":\"<p>Používame tieto cookies aby sme mohli dodávať najmä našim registrovaným užívateľom čo najlepší obsah (Bez týchto cookies registrácia nie je možná).<\\/p>\\r\\n\"}'),
('sk', '3', 'OFFLINE\\GDPR\\Models\\Cookie', '{\"name\":\"\",\"description\":\"<p>Tieto cookies n\\u00e1m pom\\u00e1haj\\u00fa sledova\\u0165 pou\\u017e\\u00edvanie na\\u0161ich str\\u00e1nok.<\\/p>\\r\\n\",\"contact_links_dpo\":\"null\",\"levels\":\"null\",\"item_details\":\"null\"}'),
('cs', '3', 'OFFLINE\\GDPR\\Models\\Cookie', '{\"name\":\"Analytick\\u00e9\",\"description\":\"<p>Tyto cookies n\\u00e1m pom\\u00e1haj\\u00ed sledovat pou\\u017e\\u00edv\\u00e1n\\u00ed na\\u0161ich str\\u00e1nek.<\\/p>\",\"contact_links_dpo\":\"[]\",\"levels\":\"[]\",\"item_details\":\"[]\"}'),
('sk', '3', 'OFFLINE\\GDPR\\Models\\CookieGroup', '{\"name\":\"\",\"description\":\"<p>Analytické cookies nám umožňujú meranie výkonu nášho webu a našich reklamných kampaní (napr. Google Analytics). Pokiaľ vypnete používanie analytických cookies vo vzťahu k Vašej návšteve, strácame možnosť analýzy výkonu a následné zlepšovanie našich stránok.<\\/p>\\r\\n\"}'),
('sk', '4', 'OFFLINE\\GDPR\\Models\\Cookie', '{\"name\":\"Reklamn\\u00e9\",\"description\":\"<p>Reklamn\\u00e9 cookies pom\\u00e1haj\\u00fa zobrazova\\u0165 reklamu na webe zalo\\u017een\\u00fa na va\\u0161ich z\\u00e1ujmoch.<\\/p>\\r\\n\",\"contact_links_dpo\":\"null\",\"levels\":\"null\",\"item_details\":\"null\"}'),
('cs', '4', 'OFFLINE\\GDPR\\Models\\Cookie', '{\"name\":\"Reklamn\\u00ed\",\"description\":\"<p>Reklamn\\u00ed cookies pom\\u00e1haj\\u00ed zobrazovat reklamu na webu zalo\\u017eenou na va\\u0161ich z\\u00e1jmech.<\\/p>\",\"contact_links_dpo\":\"[]\",\"levels\":\"[]\",\"item_details\":\"[]\"}'),
('sk', '4', 'OFFLINE\\GDPR\\Models\\CookieGroup', '{\"name\":\"Reklamné Cookies\",\"description\":\"<p>Reklamné cookies používame my alebo naši partneri, aby sme Vám mohli zobraziť vhodné obsahy alebo reklamy ako na našich stránkach, tak na stránkach tretích subjektov s využitím tzv. pseudonymizovaných profilov, ktoré neudržujú vaše osobné údaje.<\\/p>\\r\\n\"}');
